### ISSUE TITLE
Error when trying to convert pdf

### ISSUE THREAD

**Issue by HansS** [wesdoyle/pdf-to-png-ocr#1]
python raster.py 300 checklist.pdf
Traceback (most recent call last):
  File "raster.py", line 3, in <module>
    from wand.image import Image
ModuleNotFoundError: No module named 'wand'

**Comment by wesdoyle** [comment]
@HansS - please make sure that wand is installed in your environment.
`pip install wand`

**Comment by wesdoyle** [comment]
Installing `wand` dependency solves issue.
